/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schiaccialatalpa;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Principale
 */
public class GameForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameForm.class.getName());
    
    /**
     * Creates new form GameForm
     */
    public GameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBuca1 = new javax.swing.JLabel();
        lblBuca2 = new javax.swing.JLabel();
        lblBuca3 = new javax.swing.JLabel();
        lblBuca4 = new javax.swing.JLabel();
        lblBuca5 = new javax.swing.JLabel();
        lblBuca6 = new javax.swing.JLabel();
        lblBuca7 = new javax.swing.JLabel();
        lblBuca8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel2.setText("00-00");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel11.setText("-");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 40, -1));

        jLabel12.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel12.setText("PUNTEGGIO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel13.setText("TIMER");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        lblBuca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBuca1.setMaximumSize(new java.awt.Dimension(200, 200));
        lblBuca1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(lblBuca1);

        lblBuca2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca2.setText("jLabel3");
        jPanel1.add(lblBuca2);

        lblBuca3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca3.setText("jLabel5");
        jPanel1.add(lblBuca3);

        lblBuca4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca4.setText("jLabel4");
        jPanel1.add(lblBuca4);

        lblBuca5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca5.setText("jLabel6");
        jPanel1.add(lblBuca5);

        lblBuca6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca6.setText("jLabel8");
        jPanel1.add(lblBuca6);

        lblBuca7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca7.setText("jLabel9");
        jPanel1.add(lblBuca7);

        lblBuca8.setBackground(new java.awt.Color(0, 0, 0));
        lblBuca8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca8.setText("jLabel10");
        jPanel1.add(lblBuca8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        jLabel9.setText("jLabel7");
        jPanel1.add(jLabel9);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 420, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/sfondoGame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -160, 980, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuca1;
    private javax.swing.JLabel lblBuca2;
    private javax.swing.JLabel lblBuca3;
    private javax.swing.JLabel lblBuca4;
    private javax.swing.JLabel lblBuca5;
    private javax.swing.JLabel lblBuca6;
    private javax.swing.JLabel lblBuca7;
    private javax.swing.JLabel lblBuca8;
    // End of variables declaration//GEN-END:variables
}
