/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schiaccialatalpa;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import static schiaccialatalpa.tipoTalpa.ARGENTO;
import static schiaccialatalpa.tipoTalpa.BASIC;
import static schiaccialatalpa.tipoTalpa.ORO;

/**
 *
 * @author Principale
 */
public class GameForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameForm.class.getName());
    private JLabel[]buche;
    private IntBox box=new IntBox();
    private int bucaAttiva=-1;
    private int punteggio=0;
    private tipoTalpa tipoAttivo;
    private Giocatore player;
    private int tempoRimanente = 30;
    private Timer timer;
    private Gestore g;
    
    
    public GameForm() {
        initComponents();
        player=new Giocatore();
        buche=new JLabel[]{lblBuca1,lblBuca2,lblBuca3,lblBuca4,lblBuca5,lblBuca6,lblBuca7,lblBuca8,lblBuca9};
        for(int i=0;i<buche.length;i++){
            int indiceFisso=i;
            buche[i].addMouseListener(new java.awt.event.MouseAdapter(){
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt){
                    System.out.println("Hai cliccato la buca: " + indiceFisso);
                    controllaColpito(indiceFisso);
                }
            });
        }
        Gestore g=new Gestore(box,Livello.INTERMEDIO);
        g.start();
        avviaConsumatore();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimer = new javax.swing.JLabel();
        lblPunti = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBuca1 = new javax.swing.JLabel();
        lblBuca2 = new javax.swing.JLabel();
        lblBuca3 = new javax.swing.JLabel();
        lblBuca4 = new javax.swing.JLabel();
        lblBuca5 = new javax.swing.JLabel();
        lblBuca6 = new javax.swing.JLabel();
        lblBuca7 = new javax.swing.JLabel();
        lblBuca8 = new javax.swing.JLabel();
        lblBuca9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTimer.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        lblTimer.setText("00-00");
        getContentPane().add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        lblPunti.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        lblPunti.setText("-");
        getContentPane().add(lblPunti, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 90, -1));

        jLabel12.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel12.setText("PUNTEGGIO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel13.setText("TIMER");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        lblBuca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBuca1.setMaximumSize(new java.awt.Dimension(200, 200));
        lblBuca1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(lblBuca1);

        lblBuca2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca2.setText("jLabel3");
        jPanel1.add(lblBuca2);

        lblBuca3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca3.setText("jLabel5");
        jPanel1.add(lblBuca3);

        lblBuca4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca4.setText("jLabel4");
        jPanel1.add(lblBuca4);

        lblBuca5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca5.setText("jLabel6");
        jPanel1.add(lblBuca5);

        lblBuca6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca6.setText("jLabel8");
        jPanel1.add(lblBuca6);

        lblBuca7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca7.setText("jLabel9");
        jPanel1.add(lblBuca7);

        lblBuca8.setBackground(new java.awt.Color(0, 0, 0));
        lblBuca8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca8.setText("jLabel10");
        jPanel1.add(lblBuca8);

        lblBuca9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuca9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/buca2.png"))); // NOI18N
        lblBuca9.setText("jLabel7");
        jPanel1.add(lblBuca9);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 420, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schiaccialatalpa/sfondoGame.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -160, 980, 680));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuca1;
    private javax.swing.JLabel lblBuca2;
    private javax.swing.JLabel lblBuca3;
    private javax.swing.JLabel lblBuca4;
    private javax.swing.JLabel lblBuca5;
    private javax.swing.JLabel lblBuca6;
    private javax.swing.JLabel lblBuca7;
    private javax.swing.JLabel lblBuca8;
    private javax.swing.JLabel lblBuca9;
    private javax.swing.JLabel lblPunti;
    private javax.swing.JLabel lblTimer;
    // End of variables declaration//GEN-END:variables

    void resettaTutteLeBuche() {
        for(JLabel buca : buche){
            cambiaImmagineBuca(buca,"buca2.png");
        }
    }
    public void cambiaImmagineBuca(JLabel label,String nomeFile){
        try {
            
            
                    ImageIcon icona = new ImageIcon(nomeFile);
                    if (icona.getImageLoadStatus() == java.awt.MediaTracker.ERRORED) {
                    System.out.println("File NON TROVATO alla radice: " + nomeFile);
                    return;
                    }
                    // Adattiamo l'immagine ai pixel X e Y della label
                    int w = label.getWidth() > 0 ? label.getWidth() : 200;
                    int h = label.getHeight() > 0 ? label.getHeight() : 200;
                    
                    Image img = icona.getImage().getScaledInstance(w,h, Image.SCALE_SMOOTH);
                    label.setIcon(new ImageIcon(img));
                
            } 
                catch (Exception e) {
                System.out.println("Errore: " + e.getMessage());
            }
        }
    
    
        public void cambiaImmagineBuca(int ind,tipoTalpa tipo){
        String nome="";
        switch(tipo){
            case ORO:
                nome="talpaOro1.png";
                break;
            case ARGENTO:
                nome="talpaSilver.png";
                break;
            case BASIC:
                nome="talpa.png";
                break;
                
                }
                cambiaImmagineBuca(buche[ind],nome);
            }
       private void avviaConsumatore() {
    new Thread(() -> {
        while (true) {
           
            int segnale = box.leggi(); 
            
           
            java.awt.EventQueue.invokeLater(() -> {
                if (segnale == -1) {
                    if(bucaAttiva!=-1){
                        player.gestisciMancataPressione();
                        lblPunti.setText(""+player.getPunteggio());
                    }
                    resettaTutteLeBuche();
                    bucaAttiva=-1;
                    tipoAttivo=null;
                } else {
                    if(segnale<10){
                        bucaAttiva=segnale;
                        tipoAttivo=tipoTalpa.BASIC;
                    }else{
                        bucaAttiva=segnale%10;
                        int indiceTipo=segnale/10;
                        if(indiceTipo>=tipoTalpa.values().length){
                            tipoAttivo=tipoTalpa.BASIC;
                        }else{
                            tipoAttivo=tipoTalpa.values()[indiceTipo];
                        }
                    }
                    
                    if(bucaAttiva>=0&&bucaAttiva<buche.length){
                        cambiaImmagineBuca(bucaAttiva, tipoAttivo);
                    }
                   
                    
                }
            });
        }
    }).start();
  }
       private void controllaColpito(int indiceCliccato){
           System.out.println("Click su: " + indiceCliccato + " | Buca Attiva: " + bucaAttiva);
           if(indiceCliccato==bucaAttiva && bucaAttiva!=-1){
               int p=Talpa.assegnaPunti(tipoAttivo);
               player.aggiungiPunti(p);
               lblPunti.setText(""+player.getPunteggio());
               bucaAttiva=-1;
               tipoAttivo=null;
               resettaTutteLeBuche();
               
           }else{
               int penalità=Buca.gestisciColpoVuoto();
               player.aggiungiPunti(penalità);
               lblPunti.setText(""+player.getPunteggio());
           }
           
       }
       private void avviaCountdown(){
           timer=new Timer(1000,(e)->{
               tempoRimanente--;
               lblTimer.setText(tempoRimanente+"s");
               
               if(tempoRimanente<=0){
                   timer.stop();
                   g.interrupt();
                   finePartita();
               }
           
           });
       } 
       
}
    
    
    

